---
title: "Logistic Regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this example, we will perform logistic regression on iris dataset as an example.

## Load the menarche dataset
```{r}
library(MASS)
data(iris)
head(iris)
```

```{r}
iris['Species.setosa'] <- as.factor(iris$Species == 'setosa')
preprocessParams1 <- preProcess(iris[,1:4], method=c('center', 'scale'))
iris[,1:4] <- predict(preprocessParams1, iris[,1:4])
head(iris)
```


## Plot the chart
```{r echo=FALSE}
plot(iris$Sepal.Length, iris$Species.setosa)
```

## Create Logistic Regression object
```{r}
glm.out <- glm(Species.setosa ~ Sepal.Length, family="binomial", data=iris)
# Print out predictions for each group
result <- data.frame(Sepal.Length=iris$Sepal.Length, Prob=glm.out$fitted, Species.setosa=as.numeric(iris$Species.setosa)-1)
result <- result[order(result$Sepal.Length),]
```

## Plot outputs
```{r}
plot(result$Sepal.Length, result$Species.setosa, type='p')
lines(result$Sepal.Length, result$Prob, type='l', col='red')
```
